spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"

accounts:
  message: "Welcome to ZettaBank accounts related prod APIs "
  contactDetails:
    name: "Valerie - Product Owner"
    email: "valerie@zettabank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
 
